# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

'on':
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.24

      - name: Build
        run: go build -v -ldflags='-w -s' .

      - name: Add SHORT_SHA env property with commit short sha
        run: echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-7`" >> $GITHUB_ENV

      - uses: actions/upload-artifact@v4
        with:
          name: shapr-backup-linux-amd64-${{ env.SHORT_SHA }}
          path: shapr-backup

  windows:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.24

      - name: Build
        run: go build -v -ldflags='-w -s' .

      - name: Get short SHA
        run: echo "SHORT_SHA=$("${{ github.sha }}".SubString(0, 7))" >> $env:GITHUB_ENV

      - uses: actions/upload-artifact@v4
        with:
          name: shapr-backup-amd64-${{ env.SHORT_SHA }}.exe
          path: shapr-backup.exe
